# Generated by Django 5.1.3 on 2024-11-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cor", models.CharField(max_length=6)),
                ("nome", models.CharField(max_length=50)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("numero_portas", models.IntegerField()),
            ],
        ),
    ]
